### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by muneeebb** [awxkee/webp.swift#3]
Local binary target 'libwebp_ios' does not contain expected binary artifact name 'libwebp_ios'
![WhatsApp Image 2024-05-03 at 17 39 28](https://github.com/awxkee/webp.swift/assets/71586877/b823748d-a231-43a0-883b-54bfb6aac554)

**Comment by awxkee** [comment]
Try reset package cache, update packages, restart xcode, check your packages, etc.
Probably there are some conflicts with your other packages.

**Comment by muneeebb** [comment]
Just added the package in a new xcode project and Got this error.

**Comment by muneeebb** [comment]
Resolved this, was SPM version issue.
